@startuml db
entity students{
<<PK>>id number
name varchar2
} 

entity books{
<<PK>> id number
name varchar2
<<FK>>  books_id
borrow number
}  
students "1" -- "many" books


entity history{
<<PK>> id number
book_name
student_name
<<FK>>  student_id
<<FK>>  book_id

}  
students "1" -- "many" history
books "1" -- "many" history
@enduml